version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Building the Spring Boot app...
      - cd backend/demo/demo
      - chmod +x gradlew
      - ./gradlew build

artifacts:
  files:
    - backend/demo/demo/build/libs/*.jar
