version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - cd backend
      - mvn install -DskipTests
  build:
    commands:
      - echo Building the project...
      - cd backend
      - mvn package -DskipTests
artifacts:
  files:
    - backend/target/*.jar
  base-directory: backend/target
