version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Building Spring Boot app..."
      - ./gradlew build

artifacts:
  files:
    - build/libs/*.jar
